### ISSUE TITLE
BUG: @rsc-parser/react-client is published as source

### ISSUE THREAD

**Issue by vitalets** [alvarlagerlof/rsc-parser#1344]
After installing `@rsc-parser/react-client` only `src` is available in node_modules, no `dist`:
```
npm i @rsc-parser/react-client
```
<img width="40%" src="https://github.com/user-attachments/assets/16c20a1a-b029-47b3-846b-54ade39a1cf5">

**Comment by alvarlagerlof** [comment]
Should be fixed in 0.9.2 coming out now.
