### ISSUE TITLE
Explore different way of rendering inline hints

### ISSUE THREAD

**Issue by alvarlagerlof** [alvarlagerlof/rsc-parser#228]
# Problem 

This is a little bit ugly:

<img width="547" alt="image" src="https://github.com/alvarlagerlof/rsc-parser/assets/14835120/b426add6-d006-4b3b-9bd1-7032123133e9">

# Proposed solution

tbd
https://twitter.com/alvarlagerlof/status/1689197146283646977?s=20

```
<$L4
 |
 ------------------------------  This is a client ref [link]
or 
<$L4 --------------------------  This is a client ref [link
```

**Comment by flyingonionman** [comment]
in those Ascii examples, were you suggesting something formatted as such?
![Capture](https://github.com/alvarlagerlof/rsc-parser/assets/39283458/c3b06435-bf2b-4865-bc73-4538d00970fd)

**Comment by alvarlagerlof** [comment]
I'm working on a new parser using some of the react source (wip in #646), I have a new design for these there. It's inline because it made it easier to support references in various places, like in an object. 

You can see the current design on the pic in [this Tweet](https://twitter.com/alvarlagerlof/status/1744162203656204377) as well as a link to try it out. Let me know what you think!

**Comment by flyingonionman** [comment]
Oooo, looks good to me! Do you know where can I learn more about react-client related stuff? I've never seen it before

**Comment by alvarlagerlof** [comment]
Yeah hovering could be really nice. The hovercard would probably have to be limited in size, and not display the full information of the reference, because otherwise it would be too big.
