### ISSUE TITLE
Any intuition around what a "healthy" RSC payload looks like?

### ISSUE THREAD

**Issue by steve-marmalade** [alvarlagerlof/rsc-parser#781]
Hey @alvarlagerlof , thanks for creating such a helpful tool.

I wonder if you've developed any intuition around what a good RSC payload looks like? There's clearly the low-hanging fruit of seeing that e.g. some unused data is being sent over the wire.

One other thing it helped me notice is that one of the chunks was taking up a significant proportion of the overall payload size (40%). My guess is that a healthier payload would have smaller chunks, to promote more efficient streaming? But this is the kind of thing at the limit of my current understanding.

Curious if you've had any other takeaways that are worth sharing :pray:

**Comment by alvarlagerlof** [comment]
Hi, I'm happy that you're enjoying the tool!

In regards to trying to optimise the payload, my only tip is to try to ensure that you're not sending more data than you expected or planned to the browser. Things like properties in objects that are never in your code for example. 

I think that trying to optimise the shape or the structure of the payload is probably not a worthwhile effort. I've also noticed the pattern of one or a few chunks being significantly larger than the rest. Wether this has any negative effect on performance, I don't know. It might just be a side effect of how the response is split up, different module import chunks usually quite split up, and data/jsx coming in larger pieces more often. Finding a performance win here would require profiling the React code. Not something I've attempted. I leave that responsibility to the React team to figure out.
