### ISSUE TITLE
Publish 'raw' package for use in other apps + CLI

### ISSUE THREAD

**Issue by 0xdevalias** [alvarlagerlof/rsc-parser#924]
It would be really cool if the raw functionality of this parser was able to be used as a package in other (non-web) apps, and/or if there was a CLI version of it.

**Comment by alvarlagerlof** [comment]
What would you expect to get as output from it? The parsing part of the codebase is modified React source. In React it has side effects, but in the code here it's stopping early at a few points so that it can return data instead.

**Comment by 0xdevalias** [comment]
I was exploring how to parse the `self.__next_f` aspects of a Next.js v13+ app; and hacked together a really basic workaround to extract the bits I was interested in at that time; but when I saw this lib, I was kind of expecting/hoping that I might be able to 'more officially' delegate the parsing to it to be done 'properly':

- https://gist.github.com/0xdevalias/ac465fb2f7e6fded183c2a4273d21e61#react-server-components-nextjs-v13-and-webpack-notes-on-streaming-wire-format-__next_f-etc
  - ```js
    const parseJSONFromEntry = entry => {
      const jsonPart = entry.substring(entry.indexOf('[') + 1, entry.lastIndexOf(']'));
      try {
        return JSON.parse(`[${jsonPart}]`);
      } catch (e) {
        console.error("Failed to parse JSON for entry: ", entry);
        return [];  // Return an empty array or null as per error handling choice
      }
    };
    ```

I guess I haven't thought too deeply as to the 'best' output format.. but I guess the most basic version that would be useful would be the equivalent of what is output in the 'Raw data' section of the site currently; where I could pass in 1 or more lines of 'raw RSC wire format', and get back the parsed versions of it.

**Comment by alvarlagerlof** [comment]
I think I could expose [createFlightResponse from @rsc-parser/core](https://github.com/alvarlagerlof/rsc-parser/blob/main/packages/core/src/createFlightResponse.ts). I'll make a PR.

**Comment by alvarlagerlof** [comment]
I think that this is the best reference for how to use it:

https://github.com/alvarlagerlof/rsc-parser/blob/0ceab13e635f741fd8765a31ccef26ef2d6c6f43/packages/core/src/components/ViewerPayload.tsx#L51

**Comment by 0xdevalias** [comment]
> I think I could expose [createFlightResponse from @rsc-parser/core](https://github.com/alvarlagerlof/rsc-parser/blob/main/packages/core/src/createFlightResponse.ts?rgh-link-date=2024-05-10T11%3A01%3A32Z). I'll make a PR.

@alvarlagerlof Awesome, thanks for that!

---

> I think that this is the best reference for how to use it

@alvarlagerlof Skimming through the code there, it looks like it:

- sets up an array of `messages` to pass to `createFlightResponse` (which since your PR, is exposed from `@rsc-parser/core` as `unstable_createFlightResponse`
  - https://github.com/alvarlagerlof/rsc-parser/blob/0ceab13e635f741fd8765a31ccef26ef2d6c6f43/packages/core/src/components/ViewerPayload.tsx#L51-L66
- for each of the `messages`, `createFlightResponse` calls `processBinaryChunk`
  - https://github.com/alvarlagerlof/rsc-parser/blob/347b3a46d17870306da8cae7c178caa9959f1a66/packages/core/src/createFlightResponse.ts#L9-L34
- `processBinaryChunk` seems to do the deeper parsing of the actual RSC data (and calls into other functions like `processFullRow`/etc to do so)

Will need to have a bit of a play to understand how best to use this alongside my 'extract from the `script` tags' code; but thanks for exposing it! :)
