### ISSUE TITLE
How to use the Chrome extension ?

### ISSUE THREAD

**Issue by xc1427** [alvarlagerlof/rsc-parser#940]
May be I am careless ... But after installing it, I just cannot find any UI about the rsc parser in the chrome devtool. 

So could anyone comment here to help me ?

**Comment by xc1427** [comment]
Yeah, I found it. Just so wired.

**Comment by alvarlagerlof** [comment]
Glad you found it! For anyone else wondering: its in the Chrome Devtools in the same area where React Devtools is.
